[profile.default]
src = 'contracts'
libs = ['lib', '../../node_modules']
auto_detect_solc = true
bytecode_hash = 'none'
optimizer_runs = 10

[fmt]
line_length = 160
quote_style = 'single'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
